export { ModulationEngine, ModulationRouteError } from './ModulationEngine.js';
export type { ModulationEnvironment, ModulationSource, MidiReading } from './sources.js';
export {
  MODULATABLE_TARGETS,
  MODULATION_TARGET_SPANS,
  MODULATION_TICK_HZ,
  MODULATION_TICK_MS,
  MODULATION_RAMP_SEC,
  type FollowerBand,
  type FollowerSourceDescriptor,
  type LfoShape,
  type LfoSourceDescriptor,
  type MidiAftertouchSourceDescriptor,
  type MidiBendSourceDescriptor,
  type MidiCcSourceDescriptor,
  type ModulatableTarget,
  type ModulationDestination,
  type ModulationFrame,
  type ModulationRate,
  type ModulationRoute,
  type ModulationRouteConfig,
  type ModulationSourceDescriptor,
  type ModulationSourceState,
  type ModulationSourceType,
  type ModulationState,
  type SampleHoldSourceDescriptor,
  type SpeciesModulationFrame,
  type TargetDestination,
} from './types.js';
